### ISSUE TITLE
ftplib.error_perm: 550 Failed to change directory

### ISSUE THREAD

**Issue by mauztor** [roveo/zakupki#2]
`python update.py all [2018-02-21 15:13:22.257632] Starting all update [2018-02-21 15:13:22.257702] Connecting mongodb [2018-02-21 15:13:22.259446] Updating contracts [2018-02-21 15:13:22.262443] Connecting FTP [2018-02-21 15:13:22.365817] Building file list Traceback (most recent call last): File "update.py", line 115, in <module> conf[coll]['etl'](ftp, collection, args.type) File "/opt/zakupki/py/etl.py", line 22, in contracts_etl region_files = inc_files(collection, ftp, region) if update_type == 'inc' else all_files(collection, ftp, region) File "/opt/zakupki/py/utils.py", line 128, in all_files ftp.cwd('/{region}/{collection}'.format(region=folder_name, collection=collection.name)) File "/usr/lib/python2.7/ftplib.py", line 562, in cwd return self.voidcmd(cmd) File "/usr/lib/python2.7/ftplib.py", line 254, in voidcmd return self.voidresp() File "/usr/lib/python2.7/ftplib.py", line 229, in voidresp resp = self.getresp() File "/usr/lib/python2.7/ftplib.py", line 224, in getresp raise error_perm, resp ftplib.error_perm: 550 Failed to change directory.`

**Comment by roveo** [comment]
This is very old code. The folder structure on the FTP server must have changed, so the directory it's trying to get into doesn't exist. I won't be able to fix this anytime soon, but pull requests are welcome as always.
